apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "democrm.fullname" . }}-config
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PERSISTENCE: {{ .Values.config.persistence | quote }}