apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.name }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ include "democrm.fullname" . }}-mongodb:27017/{{ .Values.mongodb.auth.database }}?directConnection=false&retryWrites=true&w=majority"