apiVersion: v1
kind: Service
metadata:
  name: {{ include "democrm.fullname" . }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    {{- include "democrm.selectorLabels" . | nindent 4 }}